### ISSUE TITLE
Inconsistent updates

### ISSUE THREAD

**Issue by xrzldzlx** [Raukze/home-assistant-fitx#1]
Since Nov. 7th the updates from the sensor are very sparse. I would guess it comes from fitx itself, because they're changing their software right now

**Comment by Raukze** [comment]
You're right, I noticed it yesterday as well. There's nothing I can do about it because the sensor relies on the data which is published by fitx on their website.

**Comment by Raukze** [comment]
I also just checked and saw that some gym locations (e.g. https://www.fitx.de/fitnessstudios/berlin-alexanderplatz) do not show the graph anymore which I use for this integration. Hopefully they are not planning on changing it for all locations.

**Comment by JayReturns** [comment]
Yes this is a rather strange behavior. I noticed that too. Sometimes the graphs show up, sometimes they don't. This is how the graph in my [gym](https://www.fitx.de/fitnessstudios/worms-innenstadt-sued) looks like:


![grafik](https://user-images.githubusercontent.com/25531620/201153665-596a141d-1d81-4c29-9453-6ccf284b5794.png)

**Comment by Raukze** [comment]
But at least for my gym starting yesterday around 6 pm CET the updates are happening more frequently again.

**Comment by Raukze** [comment]
As the updates seem to work again I'm closing this issue. I also added a note to the [README](https://github.com/Raukze/home-assistant-fitx/blob/main/README.md) in release [0.0.3](https://github.com/Raukze/home-assistant-fitx/releases/tag/0.0.3) with the info that for some locations this won't work.
Thanks @xrzldzlx for opening the issue tho 🙂
