### ISSUE TITLE
😔 FitX data not available anymore

### ISSUE THREAD

**Issue by Raukze** [Raukze/home-assistant-fitx#6]
It seems that FitX is going to not show the usage graphs for any of their locations anymore. I will wait for another couple of days and if it is not coming back I guess I'll have to archive this repo.

**Comment by AlexanderBabel** [comment]
Hey there,

they are now displayed on the new members area page. E.g.: https://mein.fitx.de/studio/Zml0eDoxNTE0NjEwMTYw?v=1

<img width="376" alt="image" src="https://user-images.githubusercontent.com/13570439/202520094-1e9c0fc3-8d3d-4ad5-884a-f6e4db3b9f78.png">

**Comment by AlexanderBabel** [comment]
There is also an API endpoint available: https://mein.fitx.de/nox/public/v1/studios/1514610160/utilization

The endpoint requires the `x-tenant: fitx` header to work.

curl example: 
```
curl --request GET \
  --url https://mein.fitx.de/nox/public/v1/studios/1514610160/utilization \
  --header 'x-tenant: fitx'
```

**Comment by Raukze** [comment]
Thanks @AlexanderBabel! I'll try to change my code accordingly but I don't know when this will be. If anyone finds the time I'm happy to accept PRs.

**Comment by Raukze** [comment]
As the data is still available I'll close this issue for now.
